version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
  build:
    commands:
      - npm install
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: dist/portfolio
